name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: macOS-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
          cache: 'gradle'

      - name: Cache Kotlin Native
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-konan
          restore-keys: ${{ runner.os }}-konan

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew publishAllPublicationsToMavenCentralRepository publish --no-daemon --no-configuration-cache -i -s
        env:
          ORG_GRADLE_PROJECT_evasGithubUser: ${{ secrets.GH_USER }}
          ORG_GRADLE_PROJECT_evasGithubToken: ${{ secrets.GH_TOKEN }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

